#!/usr/bin/env python3
"""Generate _publications/*.md from the Zotero BibTeX export.

    python3 tools/build_publications.py [-b _bibliography/MyPublications.bib]

Bibliographic metadata comes from the .bib file (auto-exported by Zotero /
Better BibTeX). Everything Zotero does not hold (summary, equal-contribution
and corresponding-author flags, URL overrides...) comes from
_data/pub_extras.yml, keyed by citation key. Cover images and PDFs are picked
up by filename (images/publications/<slug>.*, files/publications/<slug>.pdf).
The generated pages are overwritten on every run: edit the extras, not them.
"""
import argparse
import glob
import json
import os
import re
import sys

import yaml

ME = "Blanc"
MARK = "# GENERATED by tools/build_publications.py - do not edit; edit _data/pub_extras.yml"
MONTHS = {m: i + 1 for i, m in enumerate(
    "jan feb mar apr may jun jul aug sep oct nov dec".split())}
ACCENTS = {  # common LaTeX accents -> unicode
    "'": {"e": "é", "a": "á", "o": "ó", "i": "í", "u": "ú", "E": "É", "c": "ć"},
    "`": {"e": "è", "a": "à", "u": "ù", "o": "ò"},
    '"': {"o": "ö", "u": "ü", "a": "ä", "e": "ë", "i": "ï", "O": "Ö", "U": "Ü"},
    "^": {"e": "ê", "o": "ô", "a": "â", "i": "î", "u": "û"},
    "~": {"n": "ñ", "a": "ã", "o": "õ"},
    "v": {"c": "č", "s": "š", "z": "ž", "r": "ř", "n": "ň"},
    "c": {"c": "ç"},
}


def parse_bib(text):
    """Minimal brace-aware BibTeX parser -> list of dicts (with 'type', 'key')."""
    entries = []
    for m in re.finditer(r"@(\w+)\s*\{\s*([^,\s]+)\s*,", text):
        etype, key = m.group(1).lower(), m.group(2)
        if etype in ("comment", "string", "preamble"):
            continue
        i, n, fields = m.end(), len(text), {}
        while i < n:
            fm = re.compile(r"\s*([\w-]+)\s*=\s*").match(text, i)
            if not fm:
                break
            name, i = fm.group(1).lower(), fm.end()
            if text[i] == "{":
                depth, j = 1, i + 1
                while depth:
                    depth += {"{": 1, "}": -1}.get(text[j], 0)
                    j += 1
                value, i = text[i + 1:j - 1], j
            elif text[i] == '"':
                j = text.index('"', i + 1)
                value, i = text[i + 1:j], j + 1
            else:
                vm = re.compile(r"[^,}\s]+").match(text, i)
                value, i = vm.group(0), vm.end()
            fields[name] = value
            cm = re.compile(r"\s*,?\s*").match(text, i)
            i = cm.end()
            if i < n and text[i] == "}":
                break
        fields.update(type=etype, key=key)
        entries.append(fields)
    return entries


def unlatex(s):
    s = re.sub(r"\\([\"'`^~vc])\s*\{?\\?([A-Za-z])\}?",
               lambda m: ACCENTS.get(m.group(1), {}).get(m.group(2), m.group(2)), s)
    s = s.replace("\\&", "&").replace("\\_", "_").replace("\\%", "%")
    s = re.sub(r"\\textsuperscript\{([^}]*)\}", r"<sup>\1</sup>", s)
    s = re.sub(r"\\textsubscript\{([^}]*)\}", r"<sub>\1</sub>", s)
    s = re.sub(r"\{\$([^$]*)\$\}", r"$\1$", s)
    s = re.sub(r"(?<!\$)\{|\}(?!\$)", "", s) if "$" not in s else s.replace("{", "").replace("}", "") \
        if "\\" not in re.sub(r"\$[^$]*\$", "", s) else s
    return re.sub(r"\s+", " ", s).strip()


def split_authors(raw):
    """BibTeX author field -> list of (first, last)."""
    names = []
    for a in re.split(r"\s+and\s+", raw.replace("\n", " ")):
        a = a.strip()
        if a.startswith("{") and a.endswith("}") and "," not in a[1:-1]:
            last, first = unlatex(a), ""  # institutional / compound surname
        elif "," in a:
            last, first = (unlatex(p) for p in a.split(",", 1))
        else:
            parts = unlatex(a).rsplit(" ", 1)
            first, last = (parts if len(parts) == 2 else ("", parts[0]))
        names.append((first.strip(), last.strip()))
    return names


def format_authors(raw, extras):
    names = split_authors(raw)
    n_eq = int(extras.get("equal_contribution", 0))
    corr = set(extras.get("corresponding", []))
    out = []
    for i, (first, last) in enumerate(names):
        full = f"{first} {last}".strip()
        if i < n_eq:
            full += "*"
        if last == ME:
            full = f"<strong>{full}</strong>"
        if last in corr:
            full += " (corr.)"
        out.append(full)
    if n_eq:
        out.append("(* equal contribution)")
    return out


def entry_date(e, extras):
    if extras.get("date"):
        return str(extras["date"])
    year = re.sub(r"\D", "", e.get("year", "")) or "1900"
    month = MONTHS.get(e.get("month", "").strip().lower()[:3],
                       int(e["month"]) if e.get("month", "").isdigit() else 1)
    return f"{year}-{month:02d}-01"


def venue(e):
    for f in ("journal", "booktitle", "publisher"):
        if e.get(f):
            return unlatex(e[f])
    if e.get("school"):
        return unlatex(e["school"]) + " (thesis)"
    return ""


def find_asset(pattern):
    hits = sorted(glob.glob(pattern))
    return "/" + hits[0] if hits else ""


def build(e, extras):
    slug = extras.get("slug", re.sub(r"[^A-Za-z0-9_-]", "", e["key"]))
    doi = re.sub(r"^https?://(dx\.)?doi\.org/", "", e.get("doi", ""))
    paperurl = extras.get("paperurl") or (f"https://doi.org/{doi}" if doi else e.get("url", ""))
    fm = {
        "title": extras.get("title") or unlatex(e.get("title", slug)),
        "collection": "publications",
        "permalink": f"/publication/{slug}",
        "date": entry_date(e, extras),
        "venue": extras.get("venue") or venue(e),
        "doi": doi,
        "paperurl": paperurl,
        "authors": extras.get("authors") or format_authors(e.get("author", ""), extras),
        "summary": extras.get("summary", ""),
        "abstract": unlatex(e.get("abstract", "")),
        "image": find_asset(f"images/publications/{slug}.*"),
        "pdf": find_asset(f"files/publications/{slug}.pdf"),
        "bibkey": e["key"],
    }
    body = "\n".join(f"{k}: {json.dumps(v, ensure_ascii=False)}" for k, v in fm.items())
    return slug, fm, f"---\n{MARK}\n{body}\n---\n\n{{% include publication-detail.html %}}\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("-b", "--bib", default="_bibliography/MyPublications.bib")
    args = ap.parse_args()
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(root)

    extras_all = yaml.safe_load(open("_data/pub_extras.yml", encoding="utf-8")) or {}
    entries = parse_bib(open(args.bib, encoding="utf-8").read())
    os.makedirs("_publications", exist_ok=True)
    written, notes, new_keys = set(), [], []
    for e in entries:
        extras = extras_all.get(e["key"], {})
        keywords = e.get("keywords", "").lower()
        if extras.get("hide") or e["type"] == "misc" or "dataset" in keywords:
            continue
        if e["key"] not in extras_all:
            new_keys.append(e["key"])
        slug, fm, text = build(e, extras)
        with open(f"_publications/{slug}.md", "w", encoding="utf-8") as f:
            f.write(text)
        written.add(f"{slug}.md")
        for what in ("summary", "image", "pdf"):
            if not fm[what]:
                notes.append(f"  {slug}: no {what}")
    if new_keys:  # append stubs, leaving the hand-edited file otherwise untouched
        with open("_data/pub_extras.yml", "a", encoding="utf-8") as f:
            f.write("".join(f'\n{k}:\n  summary: ""\n  # equal_contribution: 2\n  # corresponding: [{ME}]\n' for k in new_keys))
        print("added stubs to _data/pub_extras.yml for:", ", ".join(new_keys))
    # drop generated pages whose entry is gone from the .bib
    for path in glob.glob("_publications/*.md"):
        if os.path.basename(path) not in written and MARK in open(path, encoding="utf-8").read():
            os.remove(path)
            print("removed", path)
    for e in entries:  # a corresponding surname that matches no author is silently ignored otherwise
        extras = extras_all.get(e["key"], {})
        names = {last for _, last in split_authors(e.get("author", ""))}
        for surname in extras.get("corresponding", []):
            if surname not in names:
                print(f"warning: {e['key']}: corresponding author '{surname}' matches no author "
                      f"(authors: {', '.join(sorted(names))})", file=sys.stderr)
    unknown = sorted(set(extras_all) - {e["key"] for e in entries})
    print(f"{len(written)} publication pages written from {args.bib}")
    if notes:
        print("missing extras:\n" + "\n".join(notes))
    if unknown:
        print("extras with no matching BibTeX key:", ", ".join(unknown), file=sys.stderr)


if __name__ == "__main__":
    main()
